/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as AiLolRouteImport } from './routes/ai-lol'
import { Route as AiRouteRouteImport } from './routes/ai/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiIndexRouteImport } from './routes/ai/index'
import { Route as AiLiveRouteImport } from './routes/ai/live'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLolRoute = AiLolRouteImport.update({
  id: '/ai-lol',
  path: '/ai-lol',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRouteRoute = AiRouteRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiIndexRoute = AiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AiRouteRoute,
} as any)
const AiLiveRoute = AiLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AiRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRouteRouteWithChildren
  '/ai-lol': typeof AiLolRoute
  '/connections': typeof ConnectionsRoute
  '/device': typeof DeviceRoute
  '/settings': typeof SettingsRoute
  '/ai/live': typeof AiLiveRoute
  '/ai/': typeof AiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-lol': typeof AiLolRoute
  '/connections': typeof ConnectionsRoute
  '/device': typeof DeviceRoute
  '/settings': typeof SettingsRoute
  '/ai/live': typeof AiLiveRoute
  '/ai': typeof AiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRouteRouteWithChildren
  '/ai-lol': typeof AiLolRoute
  '/connections': typeof ConnectionsRoute
  '/device': typeof DeviceRoute
  '/settings': typeof SettingsRoute
  '/ai/live': typeof AiLiveRoute
  '/ai/': typeof AiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/ai-lol'
    | '/connections'
    | '/device'
    | '/settings'
    | '/ai/live'
    | '/ai/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-lol'
    | '/connections'
    | '/device'
    | '/settings'
    | '/ai/live'
    | '/ai'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/ai-lol'
    | '/connections'
    | '/device'
    | '/settings'
    | '/ai/live'
    | '/ai/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRouteRoute: typeof AiRouteRouteWithChildren
  AiLolRoute: typeof AiLolRoute
  ConnectionsRoute: typeof ConnectionsRoute
  DeviceRoute: typeof DeviceRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-lol': {
      id: '/ai-lol'
      path: '/ai-lol'
      fullPath: '/ai-lol'
      preLoaderRoute: typeof AiLolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/': {
      id: '/ai/'
      path: '/'
      fullPath: '/ai/'
      preLoaderRoute: typeof AiIndexRouteImport
      parentRoute: typeof AiRouteRoute
    }
    '/ai/live': {
      id: '/ai/live'
      path: '/live'
      fullPath: '/ai/live'
      preLoaderRoute: typeof AiLiveRouteImport
      parentRoute: typeof AiRouteRoute
    }
  }
}

interface AiRouteRouteChildren {
  AiLiveRoute: typeof AiLiveRoute
  AiIndexRoute: typeof AiIndexRoute
}

const AiRouteRouteChildren: AiRouteRouteChildren = {
  AiLiveRoute: AiLiveRoute,
  AiIndexRoute: AiIndexRoute,
}

const AiRouteRouteWithChildren =
  AiRouteRoute._addFileChildren(AiRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRouteRoute: AiRouteRouteWithChildren,
  AiLolRoute: AiLolRoute,
  ConnectionsRoute: ConnectionsRoute,
  DeviceRoute: DeviceRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
